import Muze, {Canvas, Layer } from './src/components';
import { Axes,
    Legend,
    LEGEND_POSITION,
    Color,
    Size,
    Shape,
    Headers,
    POSITION,
    ALIGNMENT,
    GridLines,
    GridBands,
    ScrollBar,
    SCROLL_VERTICAL,
    SCROLL_HORIZONTAL,
    html,
    Encoding,
    Tooltip,
    SideEffects,
    SpawnableSideEffect,
    SurrogateSideEffect,
    GenericSideEffect,
    Behaviours,
    GenericBehaviour,
    VolatileBehaviour
} from './src/configurations';

export default Muze;
export {
    Canvas,
    Layer,
    Axes,
    Legend,
    LEGEND_POSITION,
    Color,
    Size,
    Shape,
    Headers,
    POSITION,
    ALIGNMENT,
    GridLines,
    GridBands,
    ScrollBar,
    SCROLL_VERTICAL,
    SCROLL_HORIZONTAL,
    html,
    Encoding,
    Tooltip,
    SpawnableSideEffect,
    SurrogateSideEffect,
    GenericSideEffect,
    SideEffects,
    Behaviours,
    GenericBehaviour,
    VolatileBehaviour
};
